### ISSUE TITLE
error unsupported argument

### ISSUE THREAD

**Issue by bhushan-007** [plus3it/terraform-aws-tardigrade-ram-share#210]
rescources = [

An argument name “rescources” not expected here

An argument name “principal” not expected here

**Comment by lorengordon** [comment]
You've misspelled `resources`.

**Comment by bhushan-007** [comment]
my bad typo error.
please find my code and error .
resource "aws_ram_resource_share" "prdem_ram_glue_share" {
  count = "${var.stage}" != "dev" ? 1 : 0
  name  = "${var.name}-glue-shares"
  
  resources = [
    {
      name         = "Glue Tables"
      resource_arns = [
        "${var.stage}_xxxxxxxi",
        "${var.stage}_xxxxxxxx",
        "${var.stage}_xxxxxxxx"
      ]
       
    },
    {
      name         = "Glue Databases"
      resource_arns = [
        "glue.xxxxxxx.${var.stage}"
      ]
      
    }
  ]

  principals = [
    "${var.account_id}"
  ]
  
  permission_arns = [
           "arn:aws:ram::aws:permission/AWSRAMPermissionGlueDatabaseReadWriteForTable",
           "arn:aws:ram::aws:permission/AWSRAMPermissionGlueDatabaseReadWrite"
        ] 

}
----------------------------------
<html>
<body>


Error: Unsupported argument
--
983 | │
984 | │   on modules/glue/main.tf line 578, in resource "aws_ram_resource_share" "prdem_ram_glue_share":
985 | │  578:   resources = [
986 | │
987 | │ An argument named "resources" is not expected here.
988 | ╵
989 | ╷
990 | │ Error: Unsupported argument
991 | │
992 | │   on modules/glue/main.tf line 597, in resource "aws_ram_resource_share" "prdem_ram_glue_share":
993 | │  597:   principals = [
994 | │
995 | │ An argument named "principals" is not expected here.


</body>
</html>

**Comment by lorengordon** [comment]
I don't see anywhere in that code where you are using this module. Are you sure you opened an issue on the correct repo? 

It _looks_ like you might be trying to use the native terraform resource, instead. If you want to use this module, please see the tests directory for some example configurations.

**Comment by foolishhare** [comment]
The same problem

**Comment by foolishhare** [comment]
![image](https://user-images.githubusercontent.com/14123319/212677376-f5cd06c1-e5de-4216-9023-692bd8b8403d.png)

**Comment by lorengordon** [comment]
@foolishhare See the `tests` directory for examples of how to use this module. All tests are functional and create fully working implementations.
